# Config file for pact http server. Launch with `pact -s config.yaml`

# HTTP server port
port: 4443

# directory for HTTP logs
logDir: pact-log

# persistence directory
persistDir: pact-log

# SQLite pragmas for pact back-end
pragmas: []

# verbose: provide log output
verbose: True
